[2024-03-08 18:19:50 +0000] [894474] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:19:50 +0000] [894474] [INFO] Listening at: unix:/run/gunicorn.sock (894474)
[2024-03-08 18:19:50 +0000] [894474] [INFO] Using worker: sync
[2024-03-08 18:19:50 +0000] [894479] [INFO] Booting worker with pid: 894479
[2024-03-08 18:19:50 +0000] [894480] [INFO] Booting worker with pid: 894480
[2024-03-08 18:19:50 +0000] [894481] [INFO] Booting worker with pid: 894481
[2024-03-08 18:20:39,004] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 42, in blog_post
    processed_post = post_deserialized.replace("![](", "![](/images/_resources/")
AttributeError: 'dict' object has no attribute 'replace'
[2024-03-08 18:20:59,194] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 42, in blog_post
    processed_post = post_deserialized.replace("![](", "![](/images/_resources/")
AttributeError: 'dict' object has no attribute 'replace'
[2024-03-08 18:27:53 +0000] [894474] [INFO] Handling signal: term
[2024-03-08 18:27:53 +0000] [894479] [INFO] Worker exiting (pid: 894479)
[2024-03-08 18:27:53 +0000] [894480] [INFO] Worker exiting (pid: 894480)
[2024-03-08 18:27:53 +0000] [894481] [INFO] Worker exiting (pid: 894481)
[2024-03-08 18:27:53 +0000] [894474] [WARNING] Worker with pid 894479 was terminated due to signal 15
[2024-03-08 18:27:53 +0000] [894474] [INFO] Shutting down: Master
[2024-03-08 18:27:59 +0000] [894922] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:27:59 +0000] [894922] [INFO] Listening at: unix:/run/gunicorn.sock (894922)
[2024-03-08 18:27:59 +0000] [894922] [INFO] Using worker: sync
[2024-03-08 18:27:59 +0000] [894927] [INFO] Booting worker with pid: 894927
[2024-03-08 18:27:59 +0000] [894928] [INFO] Booting worker with pid: 894928
[2024-03-08 18:27:59 +0000] [894929] [INFO] Booting worker with pid: 894929
[2024-03-08 18:28:09,929] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:28:12,909] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:28:14,040] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:29:33 +0000] [894922] [INFO] Handling signal: term
[2024-03-08 18:29:33 +0000] [894927] [INFO] Worker exiting (pid: 894927)
[2024-03-08 18:29:33 +0000] [894928] [INFO] Worker exiting (pid: 894928)
[2024-03-08 18:29:33 +0000] [894929] [INFO] Worker exiting (pid: 894929)
[2024-03-08 18:29:33 +0000] [894922] [WARNING] Worker with pid 894927 was terminated due to signal 15
[2024-03-08 18:29:33 +0000] [894922] [INFO] Shutting down: Master
[2024-03-08 18:29:39 +0000] [895038] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:29:39 +0000] [895038] [INFO] Listening at: unix:/run/gunicorn.sock (895038)
[2024-03-08 18:29:39 +0000] [895038] [INFO] Using worker: sync
[2024-03-08 18:29:39 +0000] [895043] [INFO] Booting worker with pid: 895043
[2024-03-08 18:29:39 +0000] [895044] [INFO] Booting worker with pid: 895044
[2024-03-08 18:29:39 +0000] [895045] [INFO] Booting worker with pid: 895045
[2024-03-08 18:34:18 +0000] [895038] [INFO] Handling signal: term
[2024-03-08 18:34:18 +0000] [895043] [INFO] Worker exiting (pid: 895043)
[2024-03-08 18:34:18 +0000] [895044] [INFO] Worker exiting (pid: 895044)
[2024-03-08 18:34:18 +0000] [895045] [INFO] Worker exiting (pid: 895045)
[2024-03-08 18:34:18 +0000] [895038] [WARNING] Worker with pid 895043 was terminated due to signal 15
[2024-03-08 18:34:18 +0000] [895038] [INFO] Shutting down: Master
[2024-03-08 18:34:24 +0000] [895339] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:34:24 +0000] [895339] [INFO] Listening at: unix:/run/gunicorn.sock (895339)
[2024-03-08 18:34:24 +0000] [895339] [INFO] Using worker: sync
[2024-03-08 18:34:24 +0000] [895344] [INFO] Booting worker with pid: 895344
[2024-03-08 18:34:24 +0000] [895345] [INFO] Booting worker with pid: 895345
[2024-03-08 18:34:24 +0000] [895346] [INFO] Booting worker with pid: 895346
[2024-03-08 18:41:04 +0000] [895339] [INFO] Handling signal: term
[2024-03-08 18:41:04 +0000] [895344] [INFO] Worker exiting (pid: 895344)
[2024-03-08 18:41:04 +0000] [895345] [INFO] Worker exiting (pid: 895345)
[2024-03-08 18:41:04 +0000] [895346] [INFO] Worker exiting (pid: 895346)
[2024-03-08 18:41:04 +0000] [895339] [WARNING] Worker with pid 895346 was terminated due to signal 15
[2024-03-08 18:41:04 +0000] [895339] [WARNING] Worker with pid 895345 was terminated due to signal 15
[2024-03-08 18:41:05 +0000] [895339] [INFO] Shutting down: Master
[2024-03-08 18:41:11 +0000] [895710] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:41:11 +0000] [895710] [INFO] Listening at: unix:/run/gunicorn.sock (895710)
[2024-03-08 18:41:11 +0000] [895710] [INFO] Using worker: sync
[2024-03-08 18:41:11 +0000] [895715] [INFO] Booting worker with pid: 895715
[2024-03-08 18:41:11 +0000] [895716] [INFO] Booting worker with pid: 895716
[2024-03-08 18:41:11 +0000] [895717] [INFO] Booting worker with pid: 895717
[2024-03-08 19:03:03 +0000] [895710] [INFO] Handling signal: term
[2024-03-08 19:03:03 +0000] [895715] [INFO] Worker exiting (pid: 895715)
[2024-03-08 19:03:03 +0000] [895716] [INFO] Worker exiting (pid: 895716)
[2024-03-08 19:03:03 +0000] [895717] [INFO] Worker exiting (pid: 895717)
[2024-03-08 19:03:04 +0000] [895710] [WARNING] Worker with pid 895715 was terminated due to signal 15
[2024-03-08 19:03:04 +0000] [895710] [INFO] Shutting down: Master
[2024-03-08 19:03:10 +0000] [896618] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:03:10 +0000] [896618] [INFO] Listening at: unix:/run/gunicorn.sock (896618)
[2024-03-08 19:03:10 +0000] [896618] [INFO] Using worker: sync
[2024-03-08 19:03:10 +0000] [896623] [INFO] Booting worker with pid: 896623
[2024-03-08 19:03:10 +0000] [896624] [INFO] Booting worker with pid: 896624
[2024-03-08 19:03:10 +0000] [896625] [INFO] Booting worker with pid: 896625
[2024-03-08 19:03:12,822] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 47, in blog_post
    return render_template('blogpost.html', post=post_deserialized, post_content_test=post_content_test)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/templates/blogpost.html", line 23, in template
    <span>{{ post_content_test }</span>
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
[2024-03-08 19:03:53 +0000] [896618] [INFO] Handling signal: term
[2024-03-08 19:03:53 +0000] [896623] [INFO] Worker exiting (pid: 896623)
[2024-03-08 19:03:53 +0000] [896624] [INFO] Worker exiting (pid: 896624)
[2024-03-08 19:03:53 +0000] [896625] [INFO] Worker exiting (pid: 896625)
[2024-03-08 19:03:53 +0000] [896618] [WARNING] Worker with pid 896623 was terminated due to signal 15
[2024-03-08 19:03:53 +0000] [896618] [INFO] Shutting down: Master
[2024-03-08 19:03:59 +0000] [896731] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:03:59 +0000] [896731] [INFO] Listening at: unix:/run/gunicorn.sock (896731)
[2024-03-08 19:03:59 +0000] [896731] [INFO] Using worker: sync
[2024-03-08 19:03:59 +0000] [896736] [INFO] Booting worker with pid: 896736
[2024-03-08 19:03:59 +0000] [896737] [INFO] Booting worker with pid: 896737
[2024-03-08 19:03:59 +0000] [896738] [INFO] Booting worker with pid: 896738
[2024-03-08 19:17:13 +0000] [896731] [INFO] Handling signal: term
[2024-03-08 19:17:13 +0000] [896736] [INFO] Worker exiting (pid: 896736)
[2024-03-08 19:17:13 +0000] [896737] [INFO] Worker exiting (pid: 896737)
[2024-03-08 19:17:13 +0000] [896738] [INFO] Worker exiting (pid: 896738)
[2024-03-08 19:17:13 +0000] [896731] [WARNING] Worker with pid 896736 was terminated due to signal 15
[2024-03-08 19:17:14 +0000] [896731] [INFO] Shutting down: Master
[2024-03-08 19:17:19 +0000] [897248] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:17:19 +0000] [897248] [INFO] Listening at: unix:/run/gunicorn.sock (897248)
[2024-03-08 19:17:19 +0000] [897248] [INFO] Using worker: sync
[2024-03-08 19:17:19 +0000] [897253] [INFO] Booting worker with pid: 897253
[2024-03-08 19:17:19 +0000] [897254] [INFO] Booting worker with pid: 897254
[2024-03-08 19:17:20 +0000] [897255] [INFO] Booting worker with pid: 897255
[2024-03-08 19:20:38 +0000] [897248] [INFO] Handling signal: term
[2024-03-08 19:20:38 +0000] [897253] [INFO] Worker exiting (pid: 897253)
[2024-03-08 19:20:38 +0000] [897254] [INFO] Worker exiting (pid: 897254)
[2024-03-08 19:20:38 +0000] [897255] [INFO] Worker exiting (pid: 897255)
[2024-03-08 19:20:38 +0000] [897248] [WARNING] Worker with pid 897253 was terminated due to signal 15
[2024-03-08 19:20:38 +0000] [897248] [INFO] Shutting down: Master
[2024-03-08 19:20:44 +0000] [897422] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:20:44 +0000] [897422] [INFO] Listening at: unix:/run/gunicorn.sock (897422)
[2024-03-08 19:20:44 +0000] [897422] [INFO] Using worker: sync
[2024-03-08 19:20:44 +0000] [897427] [INFO] Booting worker with pid: 897427
[2024-03-08 19:20:44 +0000] [897428] [INFO] Booting worker with pid: 897428
[2024-03-08 19:20:44 +0000] [897429] [INFO] Booting worker with pid: 897429
[2024-03-08 19:24:38 +0000] [897422] [INFO] Handling signal: term
[2024-03-08 19:24:38 +0000] [897427] [INFO] Worker exiting (pid: 897427)
[2024-03-08 19:24:38 +0000] [897428] [INFO] Worker exiting (pid: 897428)
[2024-03-08 19:24:38 +0000] [897429] [INFO] Worker exiting (pid: 897429)
[2024-03-08 19:24:38 +0000] [897422] [WARNING] Worker with pid 897427 was terminated due to signal 15
[2024-03-08 19:24:38 +0000] [897422] [INFO] Shutting down: Master
[2024-03-08 19:24:44 +0000] [897596] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:24:44 +0000] [897596] [INFO] Listening at: unix:/run/gunicorn.sock (897596)
[2024-03-08 19:24:44 +0000] [897596] [INFO] Using worker: sync
[2024-03-08 19:24:44 +0000] [897601] [INFO] Booting worker with pid: 897601
[2024-03-08 19:24:44 +0000] [897602] [INFO] Booting worker with pid: 897602
[2024-03-08 19:24:44 +0000] [897603] [INFO] Booting worker with pid: 897603
