[2024-03-08 18:19:50 +0000] [894474] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:19:50 +0000] [894474] [INFO] Listening at: unix:/run/gunicorn.sock (894474)
[2024-03-08 18:19:50 +0000] [894474] [INFO] Using worker: sync
[2024-03-08 18:19:50 +0000] [894479] [INFO] Booting worker with pid: 894479
[2024-03-08 18:19:50 +0000] [894480] [INFO] Booting worker with pid: 894480
[2024-03-08 18:19:50 +0000] [894481] [INFO] Booting worker with pid: 894481
[2024-03-08 18:20:39,004] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 42, in blog_post
    processed_post = post_deserialized.replace("![](", "![](/images/_resources/")
AttributeError: 'dict' object has no attribute 'replace'
[2024-03-08 18:20:59,194] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 42, in blog_post
    processed_post = post_deserialized.replace("![](", "![](/images/_resources/")
AttributeError: 'dict' object has no attribute 'replace'
[2024-03-08 18:27:53 +0000] [894474] [INFO] Handling signal: term
[2024-03-08 18:27:53 +0000] [894479] [INFO] Worker exiting (pid: 894479)
[2024-03-08 18:27:53 +0000] [894480] [INFO] Worker exiting (pid: 894480)
[2024-03-08 18:27:53 +0000] [894481] [INFO] Worker exiting (pid: 894481)
[2024-03-08 18:27:53 +0000] [894474] [WARNING] Worker with pid 894479 was terminated due to signal 15
[2024-03-08 18:27:53 +0000] [894474] [INFO] Shutting down: Master
[2024-03-08 18:27:59 +0000] [894922] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:27:59 +0000] [894922] [INFO] Listening at: unix:/run/gunicorn.sock (894922)
[2024-03-08 18:27:59 +0000] [894922] [INFO] Using worker: sync
[2024-03-08 18:27:59 +0000] [894927] [INFO] Booting worker with pid: 894927
[2024-03-08 18:27:59 +0000] [894928] [INFO] Booting worker with pid: 894928
[2024-03-08 18:27:59 +0000] [894929] [INFO] Booting worker with pid: 894929
[2024-03-08 18:28:09,929] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:28:12,909] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:28:14,040] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:29:33 +0000] [894922] [INFO] Handling signal: term
[2024-03-08 18:29:33 +0000] [894927] [INFO] Worker exiting (pid: 894927)
[2024-03-08 18:29:33 +0000] [894928] [INFO] Worker exiting (pid: 894928)
[2024-03-08 18:29:33 +0000] [894929] [INFO] Worker exiting (pid: 894929)
[2024-03-08 18:29:33 +0000] [894922] [WARNING] Worker with pid 894927 was terminated due to signal 15
[2024-03-08 18:29:33 +0000] [894922] [INFO] Shutting down: Master
[2024-03-08 18:29:39 +0000] [895038] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:29:39 +0000] [895038] [INFO] Listening at: unix:/run/gunicorn.sock (895038)
[2024-03-08 18:29:39 +0000] [895038] [INFO] Using worker: sync
[2024-03-08 18:29:39 +0000] [895043] [INFO] Booting worker with pid: 895043
[2024-03-08 18:29:39 +0000] [895044] [INFO] Booting worker with pid: 895044
[2024-03-08 18:29:39 +0000] [895045] [INFO] Booting worker with pid: 895045
[2024-03-08 18:34:18 +0000] [895038] [INFO] Handling signal: term
[2024-03-08 18:34:18 +0000] [895043] [INFO] Worker exiting (pid: 895043)
[2024-03-08 18:34:18 +0000] [895044] [INFO] Worker exiting (pid: 895044)
[2024-03-08 18:34:18 +0000] [895045] [INFO] Worker exiting (pid: 895045)
[2024-03-08 18:34:18 +0000] [895038] [WARNING] Worker with pid 895043 was terminated due to signal 15
[2024-03-08 18:34:18 +0000] [895038] [INFO] Shutting down: Master
[2024-03-08 18:34:24 +0000] [895339] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:34:24 +0000] [895339] [INFO] Listening at: unix:/run/gunicorn.sock (895339)
[2024-03-08 18:34:24 +0000] [895339] [INFO] Using worker: sync
[2024-03-08 18:34:24 +0000] [895344] [INFO] Booting worker with pid: 895344
[2024-03-08 18:34:24 +0000] [895345] [INFO] Booting worker with pid: 895345
[2024-03-08 18:34:24 +0000] [895346] [INFO] Booting worker with pid: 895346
[2024-03-08 18:41:04 +0000] [895339] [INFO] Handling signal: term
[2024-03-08 18:41:04 +0000] [895344] [INFO] Worker exiting (pid: 895344)
[2024-03-08 18:41:04 +0000] [895345] [INFO] Worker exiting (pid: 895345)
[2024-03-08 18:41:04 +0000] [895346] [INFO] Worker exiting (pid: 895346)
[2024-03-08 18:41:04 +0000] [895339] [WARNING] Worker with pid 895346 was terminated due to signal 15
[2024-03-08 18:41:04 +0000] [895339] [WARNING] Worker with pid 895345 was terminated due to signal 15
[2024-03-08 18:41:05 +0000] [895339] [INFO] Shutting down: Master
[2024-03-08 18:41:11 +0000] [895710] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:41:11 +0000] [895710] [INFO] Listening at: unix:/run/gunicorn.sock (895710)
[2024-03-08 18:41:11 +0000] [895710] [INFO] Using worker: sync
[2024-03-08 18:41:11 +0000] [895715] [INFO] Booting worker with pid: 895715
[2024-03-08 18:41:11 +0000] [895716] [INFO] Booting worker with pid: 895716
[2024-03-08 18:41:11 +0000] [895717] [INFO] Booting worker with pid: 895717
[2024-03-08 19:03:03 +0000] [895710] [INFO] Handling signal: term
[2024-03-08 19:03:03 +0000] [895715] [INFO] Worker exiting (pid: 895715)
[2024-03-08 19:03:03 +0000] [895716] [INFO] Worker exiting (pid: 895716)
[2024-03-08 19:03:03 +0000] [895717] [INFO] Worker exiting (pid: 895717)
[2024-03-08 19:03:04 +0000] [895710] [WARNING] Worker with pid 895715 was terminated due to signal 15
[2024-03-08 19:03:04 +0000] [895710] [INFO] Shutting down: Master
[2024-03-08 19:03:10 +0000] [896618] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:03:10 +0000] [896618] [INFO] Listening at: unix:/run/gunicorn.sock (896618)
[2024-03-08 19:03:10 +0000] [896618] [INFO] Using worker: sync
[2024-03-08 19:03:10 +0000] [896623] [INFO] Booting worker with pid: 896623
[2024-03-08 19:03:10 +0000] [896624] [INFO] Booting worker with pid: 896624
[2024-03-08 19:03:10 +0000] [896625] [INFO] Booting worker with pid: 896625
[2024-03-08 19:03:12,822] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 47, in blog_post
    return render_template('blogpost.html', post=post_deserialized, post_content_test=post_content_test)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/templates/blogpost.html", line 23, in template
    <span>{{ post_content_test }</span>
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
[2024-03-08 19:03:53 +0000] [896618] [INFO] Handling signal: term
[2024-03-08 19:03:53 +0000] [896623] [INFO] Worker exiting (pid: 896623)
[2024-03-08 19:03:53 +0000] [896624] [INFO] Worker exiting (pid: 896624)
[2024-03-08 19:03:53 +0000] [896625] [INFO] Worker exiting (pid: 896625)
[2024-03-08 19:03:53 +0000] [896618] [WARNING] Worker with pid 896623 was terminated due to signal 15
[2024-03-08 19:03:53 +0000] [896618] [INFO] Shutting down: Master
[2024-03-08 19:03:59 +0000] [896731] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:03:59 +0000] [896731] [INFO] Listening at: unix:/run/gunicorn.sock (896731)
[2024-03-08 19:03:59 +0000] [896731] [INFO] Using worker: sync
[2024-03-08 19:03:59 +0000] [896736] [INFO] Booting worker with pid: 896736
[2024-03-08 19:03:59 +0000] [896737] [INFO] Booting worker with pid: 896737
[2024-03-08 19:03:59 +0000] [896738] [INFO] Booting worker with pid: 896738
[2024-03-08 19:17:13 +0000] [896731] [INFO] Handling signal: term
[2024-03-08 19:17:13 +0000] [896736] [INFO] Worker exiting (pid: 896736)
[2024-03-08 19:17:13 +0000] [896737] [INFO] Worker exiting (pid: 896737)
[2024-03-08 19:17:13 +0000] [896738] [INFO] Worker exiting (pid: 896738)
[2024-03-08 19:17:13 +0000] [896731] [WARNING] Worker with pid 896736 was terminated due to signal 15
[2024-03-08 19:17:14 +0000] [896731] [INFO] Shutting down: Master
[2024-03-08 19:17:19 +0000] [897248] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:17:19 +0000] [897248] [INFO] Listening at: unix:/run/gunicorn.sock (897248)
[2024-03-08 19:17:19 +0000] [897248] [INFO] Using worker: sync
[2024-03-08 19:17:19 +0000] [897253] [INFO] Booting worker with pid: 897253
[2024-03-08 19:17:19 +0000] [897254] [INFO] Booting worker with pid: 897254
[2024-03-08 19:17:20 +0000] [897255] [INFO] Booting worker with pid: 897255
[2024-03-08 19:20:38 +0000] [897248] [INFO] Handling signal: term
[2024-03-08 19:20:38 +0000] [897253] [INFO] Worker exiting (pid: 897253)
[2024-03-08 19:20:38 +0000] [897254] [INFO] Worker exiting (pid: 897254)
[2024-03-08 19:20:38 +0000] [897255] [INFO] Worker exiting (pid: 897255)
[2024-03-08 19:20:38 +0000] [897248] [WARNING] Worker with pid 897253 was terminated due to signal 15
[2024-03-08 19:20:38 +0000] [897248] [INFO] Shutting down: Master
[2024-03-08 19:20:44 +0000] [897422] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:20:44 +0000] [897422] [INFO] Listening at: unix:/run/gunicorn.sock (897422)
[2024-03-08 19:20:44 +0000] [897422] [INFO] Using worker: sync
[2024-03-08 19:20:44 +0000] [897427] [INFO] Booting worker with pid: 897427
[2024-03-08 19:20:44 +0000] [897428] [INFO] Booting worker with pid: 897428
[2024-03-08 19:20:44 +0000] [897429] [INFO] Booting worker with pid: 897429
[2024-03-08 19:24:38 +0000] [897422] [INFO] Handling signal: term
[2024-03-08 19:24:38 +0000] [897427] [INFO] Worker exiting (pid: 897427)
[2024-03-08 19:24:38 +0000] [897428] [INFO] Worker exiting (pid: 897428)
[2024-03-08 19:24:38 +0000] [897429] [INFO] Worker exiting (pid: 897429)
[2024-03-08 19:24:38 +0000] [897422] [WARNING] Worker with pid 897427 was terminated due to signal 15
[2024-03-08 19:24:38 +0000] [897422] [INFO] Shutting down: Master
[2024-03-08 19:24:44 +0000] [897596] [INFO] Starting gunicorn 20.1.0
[2024-03-08 19:24:44 +0000] [897596] [INFO] Listening at: unix:/run/gunicorn.sock (897596)
[2024-03-08 19:24:44 +0000] [897596] [INFO] Using worker: sync
[2024-03-08 19:24:44 +0000] [897601] [INFO] Booting worker with pid: 897601
[2024-03-08 19:24:44 +0000] [897602] [INFO] Booting worker with pid: 897602
[2024-03-08 19:24:44 +0000] [897603] [INFO] Booting worker with pid: 897603
[2024-03-08 20:48:53 +0000] [897596] [INFO] Handling signal: term
[2024-03-08 20:48:53 +0000] [897601] [INFO] Worker exiting (pid: 897601)
[2024-03-08 20:48:53 +0000] [897602] [INFO] Worker exiting (pid: 897602)
[2024-03-08 20:48:53 +0000] [897603] [INFO] Worker exiting (pid: 897603)
[2024-03-08 20:48:53 +0000] [897596] [WARNING] Worker with pid 897601 was terminated due to signal 15
[2024-03-08 20:48:54 +0000] [897596] [INFO] Shutting down: Master
[2024-03-08 20:48:59 +0000] [900507] [INFO] Starting gunicorn 20.1.0
[2024-03-08 20:48:59 +0000] [900507] [INFO] Listening at: unix:/run/gunicorn.sock (900507)
[2024-03-08 20:48:59 +0000] [900507] [INFO] Using worker: sync
[2024-03-08 20:48:59 +0000] [900566] [INFO] Booting worker with pid: 900566
[2024-03-08 20:48:59 +0000] [900567] [INFO] Booting worker with pid: 900567
[2024-03-08 20:48:59 +0000] [900568] [INFO] Booting worker with pid: 900568
[2024-03-08 20:50:23 +0000] [900507] [INFO] Handling signal: term
[2024-03-08 20:50:23 +0000] [900568] [INFO] Worker exiting (pid: 900568)
[2024-03-08 20:50:23 +0000] [900567] [INFO] Worker exiting (pid: 900567)
[2024-03-08 20:50:23 +0000] [900566] [INFO] Worker exiting (pid: 900566)
[2024-03-08 20:50:23 +0000] [900507] [WARNING] Worker with pid 900568 was terminated due to signal 15
[2024-03-08 20:50:24 +0000] [900507] [INFO] Shutting down: Master
[2024-03-08 20:50:24 +0000] [900667] [INFO] Starting gunicorn 20.1.0
[2024-03-08 20:50:24 +0000] [900667] [INFO] Listening at: unix:/run/gunicorn.sock (900667)
[2024-03-08 20:50:24 +0000] [900667] [INFO] Using worker: sync
[2024-03-08 20:50:24 +0000] [900671] [INFO] Booting worker with pid: 900671
[2024-03-08 20:50:24 +0000] [900672] [INFO] Booting worker with pid: 900672
[2024-03-08 20:50:24 +0000] [900673] [INFO] Booting worker with pid: 900673
[2024-03-08 20:54:53 +0000] [900667] [INFO] Handling signal: term
[2024-03-08 20:54:53 +0000] [900671] [INFO] Worker exiting (pid: 900671)
[2024-03-08 20:54:53 +0000] [900672] [INFO] Worker exiting (pid: 900672)
[2024-03-08 20:54:53 +0000] [900673] [INFO] Worker exiting (pid: 900673)
[2024-03-08 20:54:53 +0000] [900667] [WARNING] Worker with pid 900671 was terminated due to signal 15
[2024-03-08 20:54:54 +0000] [900667] [INFO] Shutting down: Master
[2024-03-08 20:55:00 +0000] [900838] [INFO] Starting gunicorn 20.1.0
[2024-03-08 20:55:00 +0000] [900838] [INFO] Listening at: unix:/run/gunicorn.sock (900838)
[2024-03-08 20:55:00 +0000] [900838] [INFO] Using worker: sync
[2024-03-08 20:55:00 +0000] [900896] [INFO] Booting worker with pid: 900896
[2024-03-08 20:55:00 +0000] [900897] [INFO] Booting worker with pid: 900897
[2024-03-08 20:55:00 +0000] [900898] [INFO] Booting worker with pid: 900898
[2024-03-08 21:01:48 +0000] [900838] [INFO] Handling signal: term
[2024-03-08 21:01:48 +0000] [900896] [INFO] Worker exiting (pid: 900896)
[2024-03-08 21:01:48 +0000] [900897] [INFO] Worker exiting (pid: 900897)
[2024-03-08 21:01:48 +0000] [900898] [INFO] Worker exiting (pid: 900898)
[2024-03-08 21:01:48 +0000] [900838] [WARNING] Worker with pid 900896 was terminated due to signal 15
[2024-03-08 21:01:49 +0000] [900838] [INFO] Shutting down: Master
[2024-03-08 21:01:55 +0000] [901244] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:01:55 +0000] [901244] [INFO] Listening at: unix:/run/gunicorn.sock (901244)
[2024-03-08 21:01:55 +0000] [901244] [INFO] Using worker: sync
[2024-03-08 21:01:55 +0000] [901249] [INFO] Booting worker with pid: 901249
[2024-03-08 21:01:55 +0000] [901250] [INFO] Booting worker with pid: 901250
[2024-03-08 21:01:55 +0000] [901251] [INFO] Booting worker with pid: 901251
[2024-03-08 21:03:04 +0000] [901244] [INFO] Handling signal: term
[2024-03-08 21:03:04 +0000] [901249] [INFO] Worker exiting (pid: 901249)
[2024-03-08 21:03:04 +0000] [901250] [INFO] Worker exiting (pid: 901250)
[2024-03-08 21:03:04 +0000] [901251] [INFO] Worker exiting (pid: 901251)
[2024-03-08 21:03:05 +0000] [901244] [INFO] Shutting down: Master
[2024-03-08 21:03:06 +0000] [901347] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:03:06 +0000] [901347] [INFO] Listening at: unix:/run/gunicorn.sock (901347)
[2024-03-08 21:03:06 +0000] [901347] [INFO] Using worker: sync
[2024-03-08 21:03:06 +0000] [901350] [INFO] Booting worker with pid: 901350
[2024-03-08 21:03:06 +0000] [901351] [INFO] Booting worker with pid: 901351
[2024-03-08 21:03:06 +0000] [901352] [INFO] Booting worker with pid: 901352
[2024-03-08 21:05:18 +0000] [901347] [INFO] Handling signal: term
[2024-03-08 21:05:18 +0000] [901350] [INFO] Worker exiting (pid: 901350)
[2024-03-08 21:05:18 +0000] [901351] [INFO] Worker exiting (pid: 901351)
[2024-03-08 21:05:18 +0000] [901352] [INFO] Worker exiting (pid: 901352)
[2024-03-08 21:05:18 +0000] [901347] [WARNING] Worker with pid 901350 was terminated due to signal 15
[2024-03-08 21:05:19 +0000] [901347] [INFO] Shutting down: Master
[2024-03-08 21:05:20 +0000] [901453] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:05:20 +0000] [901453] [INFO] Listening at: unix:/run/gunicorn.sock (901453)
[2024-03-08 21:05:20 +0000] [901453] [INFO] Using worker: sync
[2024-03-08 21:05:20 +0000] [901456] [INFO] Booting worker with pid: 901456
[2024-03-08 21:05:20 +0000] [901457] [INFO] Booting worker with pid: 901457
[2024-03-08 21:05:20 +0000] [901458] [INFO] Booting worker with pid: 901458
[2024-03-08 21:08:14 +0000] [901453] [INFO] Handling signal: term
[2024-03-08 21:08:14 +0000] [901456] [INFO] Worker exiting (pid: 901456)
[2024-03-08 21:08:14 +0000] [901457] [INFO] Worker exiting (pid: 901457)
[2024-03-08 21:08:14 +0000] [901458] [INFO] Worker exiting (pid: 901458)
[2024-03-08 21:08:14 +0000] [901453] [WARNING] Worker with pid 901456 was terminated due to signal 15
[2024-03-08 21:08:14 +0000] [901453] [INFO] Shutting down: Master
[2024-03-08 21:08:15 +0000] [901619] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:08:15 +0000] [901619] [INFO] Listening at: unix:/run/gunicorn.sock (901619)
[2024-03-08 21:08:15 +0000] [901619] [INFO] Using worker: sync
[2024-03-08 21:08:15 +0000] [901622] [INFO] Booting worker with pid: 901622
[2024-03-08 21:08:15 +0000] [901623] [INFO] Booting worker with pid: 901623
[2024-03-08 21:08:15 +0000] [901624] [INFO] Booting worker with pid: 901624
[2024-03-08 21:09:19 +0000] [901619] [INFO] Handling signal: term
[2024-03-08 21:09:19 +0000] [901622] [INFO] Worker exiting (pid: 901622)
[2024-03-08 21:09:19 +0000] [901623] [INFO] Worker exiting (pid: 901623)
[2024-03-08 21:09:19 +0000] [901624] [INFO] Worker exiting (pid: 901624)
[2024-03-08 21:09:19 +0000] [901619] [WARNING] Worker with pid 901622 was terminated due to signal 15
[2024-03-08 21:09:19 +0000] [901619] [INFO] Shutting down: Master
[2024-03-08 21:09:21 +0000] [901723] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:09:21 +0000] [901723] [INFO] Listening at: unix:/run/gunicorn.sock (901723)
[2024-03-08 21:09:21 +0000] [901723] [INFO] Using worker: sync
[2024-03-08 21:09:21 +0000] [901726] [INFO] Booting worker with pid: 901726
[2024-03-08 21:09:21 +0000] [901727] [INFO] Booting worker with pid: 901727
[2024-03-08 21:09:21 +0000] [901728] [INFO] Booting worker with pid: 901728
[2024-03-08 21:14:28 +0000] [901723] [INFO] Handling signal: term
[2024-03-08 21:14:28 +0000] [901726] [INFO] Worker exiting (pid: 901726)
[2024-03-08 21:14:28 +0000] [901727] [INFO] Worker exiting (pid: 901727)
[2024-03-08 21:14:28 +0000] [901728] [INFO] Worker exiting (pid: 901728)
[2024-03-08 21:14:28 +0000] [901723] [WARNING] Worker with pid 901726 was terminated due to signal 15
[2024-03-08 21:14:29 +0000] [901723] [INFO] Shutting down: Master
[2024-03-08 21:14:30 +0000] [901947] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:30 +0000] [901947] [INFO] Listening at: unix:/run/gunicorn.sock (901947)
[2024-03-08 21:14:30 +0000] [901947] [INFO] Using worker: sync
[2024-03-08 21:14:30 +0000] [901951] [INFO] Booting worker with pid: 901951
[2024-03-08 21:14:30 +0000] [901952] [INFO] Booting worker with pid: 901952
[2024-03-08 21:14:30 +0000] [901953] [INFO] Booting worker with pid: 901953
[2024-03-08 21:14:31 +0000] [901951] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:31 +0000] [901951] [INFO] Worker exiting (pid: 901951)
[2024-03-08 21:14:32 +0000] [901952] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:32 +0000] [901952] [INFO] Worker exiting (pid: 901952)
[2024-03-08 21:14:32 +0000] [901953] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:32 +0000] [901953] [INFO] Worker exiting (pid: 901953)
[2024-03-08 21:14:32 +0000] [901947] [WARNING] Worker with pid 901952 was terminated due to signal 15
[2024-03-08 21:14:32 +0000] [901947] [WARNING] Worker with pid 901953 was terminated due to signal 15
[2024-03-08 21:14:32 +0000] [901947] [INFO] Shutting down: Master
[2024-03-08 21:14:32 +0000] [901947] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:33 +0000] [901955] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:33 +0000] [901955] [INFO] Listening at: unix:/run/gunicorn.sock (901955)
[2024-03-08 21:14:33 +0000] [901955] [INFO] Using worker: sync
[2024-03-08 21:14:33 +0000] [901958] [INFO] Booting worker with pid: 901958
[2024-03-08 21:14:33 +0000] [901959] [INFO] Booting worker with pid: 901959
[2024-03-08 21:14:33 +0000] [901960] [INFO] Booting worker with pid: 901960
[2024-03-08 21:14:35 +0000] [901958] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:35 +0000] [901958] [INFO] Worker exiting (pid: 901958)
[2024-03-08 21:14:35 +0000] [901959] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:35 +0000] [901959] [INFO] Worker exiting (pid: 901959)
[2024-03-08 21:14:35 +0000] [901960] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:35 +0000] [901960] [INFO] Worker exiting (pid: 901960)
[2024-03-08 21:14:35 +0000] [901955] [WARNING] Worker with pid 901960 was terminated due to signal 15
[2024-03-08 21:14:35 +0000] [901955] [WARNING] Worker with pid 901959 was terminated due to signal 15
[2024-03-08 21:14:35 +0000] [901955] [INFO] Shutting down: Master
[2024-03-08 21:14:35 +0000] [901955] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:36 +0000] [901964] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:36 +0000] [901964] [INFO] Listening at: unix:/run/gunicorn.sock (901964)
[2024-03-08 21:14:36 +0000] [901964] [INFO] Using worker: sync
[2024-03-08 21:14:36 +0000] [901967] [INFO] Booting worker with pid: 901967
[2024-03-08 21:14:36 +0000] [901968] [INFO] Booting worker with pid: 901968
[2024-03-08 21:14:36 +0000] [901969] [INFO] Booting worker with pid: 901969
[2024-03-08 21:14:38 +0000] [901967] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:38 +0000] [901967] [INFO] Worker exiting (pid: 901967)
[2024-03-08 21:14:38 +0000] [901968] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:38 +0000] [901968] [INFO] Worker exiting (pid: 901968)
[2024-03-08 21:14:38 +0000] [901969] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:38 +0000] [901969] [INFO] Worker exiting (pid: 901969)
[2024-03-08 21:14:39 +0000] [901964] [WARNING] Worker with pid 901969 was terminated due to signal 15
[2024-03-08 21:14:39 +0000] [901964] [WARNING] Worker with pid 901967 was terminated due to signal 15
[2024-03-08 21:14:39 +0000] [901964] [INFO] Shutting down: Master
[2024-03-08 21:14:39 +0000] [901964] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:40 +0000] [901970] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:40 +0000] [901970] [INFO] Listening at: unix:/run/gunicorn.sock (901970)
[2024-03-08 21:14:40 +0000] [901970] [INFO] Using worker: sync
[2024-03-08 21:14:40 +0000] [901973] [INFO] Booting worker with pid: 901973
[2024-03-08 21:14:40 +0000] [901974] [INFO] Booting worker with pid: 901974
[2024-03-08 21:14:40 +0000] [901975] [INFO] Booting worker with pid: 901975
[2024-03-08 21:14:41 +0000] [901973] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:41 +0000] [901973] [INFO] Worker exiting (pid: 901973)
[2024-03-08 21:14:42 +0000] [901974] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:42 +0000] [901974] [INFO] Worker exiting (pid: 901974)
[2024-03-08 21:14:42 +0000] [901975] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:42 +0000] [901975] [INFO] Worker exiting (pid: 901975)
[2024-03-08 21:14:42 +0000] [901970] [WARNING] Worker with pid 901974 was terminated due to signal 15
[2024-03-08 21:14:42 +0000] [901970] [WARNING] Worker with pid 901975 was terminated due to signal 15
[2024-03-08 21:14:42 +0000] [901970] [INFO] Shutting down: Master
[2024-03-08 21:14:42 +0000] [901970] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:43 +0000] [901976] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:43 +0000] [901976] [INFO] Listening at: unix:/run/gunicorn.sock (901976)
[2024-03-08 21:14:43 +0000] [901976] [INFO] Using worker: sync
[2024-03-08 21:14:43 +0000] [901979] [INFO] Booting worker with pid: 901979
[2024-03-08 21:14:43 +0000] [901980] [INFO] Booting worker with pid: 901980
[2024-03-08 21:14:43 +0000] [901981] [INFO] Booting worker with pid: 901981
[2024-03-08 21:14:45 +0000] [901979] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:45 +0000] [901979] [INFO] Worker exiting (pid: 901979)
[2024-03-08 21:14:45 +0000] [901980] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:45 +0000] [901980] [INFO] Worker exiting (pid: 901980)
[2024-03-08 21:14:45 +0000] [901981] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:45 +0000] [901981] [INFO] Worker exiting (pid: 901981)
[2024-03-08 21:14:45 +0000] [901976] [WARNING] Worker with pid 901981 was terminated due to signal 15
[2024-03-08 21:14:45 +0000] [901976] [WARNING] Worker with pid 901980 was terminated due to signal 15
[2024-03-08 21:14:45 +0000] [901976] [INFO] Shutting down: Master
[2024-03-08 21:14:45 +0000] [901976] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:46 +0000] [901983] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:46 +0000] [901983] [INFO] Listening at: unix:/run/gunicorn.sock (901983)
[2024-03-08 21:14:46 +0000] [901983] [INFO] Using worker: sync
[2024-03-08 21:14:46 +0000] [901986] [INFO] Booting worker with pid: 901986
[2024-03-08 21:14:46 +0000] [901987] [INFO] Booting worker with pid: 901987
[2024-03-08 21:14:46 +0000] [901988] [INFO] Booting worker with pid: 901988
[2024-03-08 21:14:48 +0000] [901986] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:48 +0000] [901986] [INFO] Worker exiting (pid: 901986)
[2024-03-08 21:14:48 +0000] [901987] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:48 +0000] [901987] [INFO] Worker exiting (pid: 901987)
[2024-03-08 21:14:48 +0000] [901988] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:48 +0000] [901988] [INFO] Worker exiting (pid: 901988)
[2024-03-08 21:14:49 +0000] [901983] [WARNING] Worker with pid 901987 was terminated due to signal 15
[2024-03-08 21:14:49 +0000] [901983] [WARNING] Worker with pid 901988 was terminated due to signal 15
[2024-03-08 21:14:49 +0000] [901983] [INFO] Shutting down: Master
[2024-03-08 21:14:49 +0000] [901983] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:49 +0000] [901989] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:49 +0000] [901989] [INFO] Listening at: unix:/run/gunicorn.sock (901989)
[2024-03-08 21:14:49 +0000] [901989] [INFO] Using worker: sync
[2024-03-08 21:14:49 +0000] [901992] [INFO] Booting worker with pid: 901992
[2024-03-08 21:14:49 +0000] [901993] [INFO] Booting worker with pid: 901993
[2024-03-08 21:14:49 +0000] [901994] [INFO] Booting worker with pid: 901994
[2024-03-08 21:14:51 +0000] [901992] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:51 +0000] [901992] [INFO] Worker exiting (pid: 901992)
[2024-03-08 21:14:51 +0000] [901994] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:51 +0000] [901993] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:51 +0000] [901993] [INFO] Worker exiting (pid: 901993)
[2024-03-08 21:14:51 +0000] [901994] [INFO] Worker exiting (pid: 901994)
[2024-03-08 21:14:52 +0000] [901989] [WARNING] Worker with pid 901994 was terminated due to signal 15
[2024-03-08 21:14:52 +0000] [901989] [WARNING] Worker with pid 901993 was terminated due to signal 15
[2024-03-08 21:14:52 +0000] [901989] [INFO] Shutting down: Master
[2024-03-08 21:14:52 +0000] [901989] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:53 +0000] [901995] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:53 +0000] [901995] [INFO] Listening at: unix:/run/gunicorn.sock (901995)
[2024-03-08 21:14:53 +0000] [901995] [INFO] Using worker: sync
[2024-03-08 21:14:53 +0000] [901998] [INFO] Booting worker with pid: 901998
[2024-03-08 21:14:53 +0000] [901999] [INFO] Booting worker with pid: 901999
[2024-03-08 21:14:53 +0000] [902000] [INFO] Booting worker with pid: 902000
[2024-03-08 21:14:55 +0000] [901998] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:55 +0000] [901998] [INFO] Worker exiting (pid: 901998)
[2024-03-08 21:14:55 +0000] [901999] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:55 +0000] [901999] [INFO] Worker exiting (pid: 901999)
[2024-03-08 21:14:55 +0000] [902000] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:55 +0000] [902000] [INFO] Worker exiting (pid: 902000)
[2024-03-08 21:14:55 +0000] [901995] [WARNING] Worker with pid 901999 was terminated due to signal 15
[2024-03-08 21:14:55 +0000] [901995] [WARNING] Worker with pid 902000 was terminated due to signal 15
[2024-03-08 21:14:55 +0000] [901995] [INFO] Shutting down: Master
[2024-03-08 21:14:55 +0000] [901995] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:56 +0000] [902001] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:56 +0000] [902001] [INFO] Listening at: unix:/run/gunicorn.sock (902001)
[2024-03-08 21:14:56 +0000] [902001] [INFO] Using worker: sync
[2024-03-08 21:14:56 +0000] [902004] [INFO] Booting worker with pid: 902004
[2024-03-08 21:14:56 +0000] [902005] [INFO] Booting worker with pid: 902005
[2024-03-08 21:14:56 +0000] [902006] [INFO] Booting worker with pid: 902006
[2024-03-08 21:14:58 +0000] [902004] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:58 +0000] [902004] [INFO] Worker exiting (pid: 902004)
[2024-03-08 21:14:58 +0000] [902005] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:58 +0000] [902005] [INFO] Worker exiting (pid: 902005)
[2024-03-08 21:14:58 +0000] [902006] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:14:58 +0000] [902006] [INFO] Worker exiting (pid: 902006)
[2024-03-08 21:14:58 +0000] [902001] [WARNING] Worker with pid 902005 was terminated due to signal 15
[2024-03-08 21:14:58 +0000] [902001] [WARNING] Worker with pid 902006 was terminated due to signal 15
[2024-03-08 21:14:58 +0000] [902001] [INFO] Shutting down: Master
[2024-03-08 21:14:58 +0000] [902001] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:14:59 +0000] [902007] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:14:59 +0000] [902007] [INFO] Listening at: unix:/run/gunicorn.sock (902007)
[2024-03-08 21:14:59 +0000] [902007] [INFO] Using worker: sync
[2024-03-08 21:14:59 +0000] [902010] [INFO] Booting worker with pid: 902010
[2024-03-08 21:14:59 +0000] [902011] [INFO] Booting worker with pid: 902011
[2024-03-08 21:14:59 +0000] [902012] [INFO] Booting worker with pid: 902012
[2024-03-08 21:15:01 +0000] [902010] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:01 +0000] [902010] [INFO] Worker exiting (pid: 902010)
[2024-03-08 21:15:01 +0000] [902011] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:01 +0000] [902011] [INFO] Worker exiting (pid: 902011)
[2024-03-08 21:15:01 +0000] [902012] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:01 +0000] [902012] [INFO] Worker exiting (pid: 902012)
[2024-03-08 21:15:02 +0000] [902007] [WARNING] Worker with pid 902012 was terminated due to signal 15
[2024-03-08 21:15:02 +0000] [902007] [WARNING] Worker with pid 902011 was terminated due to signal 15
[2024-03-08 21:15:02 +0000] [902007] [INFO] Shutting down: Master
[2024-03-08 21:15:02 +0000] [902007] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:15:03 +0000] [902017] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:15:03 +0000] [902017] [INFO] Listening at: unix:/run/gunicorn.sock (902017)
[2024-03-08 21:15:03 +0000] [902017] [INFO] Using worker: sync
[2024-03-08 21:15:03 +0000] [902074] [INFO] Booting worker with pid: 902074
[2024-03-08 21:15:03 +0000] [902075] [INFO] Booting worker with pid: 902075
[2024-03-08 21:15:03 +0000] [902076] [INFO] Booting worker with pid: 902076
[2024-03-08 21:15:05 +0000] [902074] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:05 +0000] [902074] [INFO] Worker exiting (pid: 902074)
[2024-03-08 21:15:06 +0000] [902075] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:06 +0000] [902075] [INFO] Worker exiting (pid: 902075)
[2024-03-08 21:15:06 +0000] [902076] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:06 +0000] [902076] [INFO] Worker exiting (pid: 902076)
[2024-03-08 21:15:06 +0000] [902017] [WARNING] Worker with pid 902075 was terminated due to signal 15
[2024-03-08 21:15:06 +0000] [902017] [WARNING] Worker with pid 902076 was terminated due to signal 15
[2024-03-08 21:15:06 +0000] [902017] [INFO] Shutting down: Master
[2024-03-08 21:15:06 +0000] [902017] [INFO] Reason: Worker failed to boot.
[2024-03-08 21:15:10 +0000] [902077] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:15:10 +0000] [902077] [INFO] Listening at: unix:/run/gunicorn.sock (902077)
[2024-03-08 21:15:10 +0000] [902077] [INFO] Using worker: sync
[2024-03-08 21:15:10 +0000] [902080] [INFO] Booting worker with pid: 902080
[2024-03-08 21:15:10 +0000] [902081] [INFO] Booting worker with pid: 902081
[2024-03-08 21:15:10 +0000] [902082] [INFO] Booting worker with pid: 902082
[2024-03-08 21:15:12 +0000] [902080] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:12 +0000] [902080] [INFO] Worker exiting (pid: 902080)
[2024-03-08 21:15:12 +0000] [902081] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:12 +0000] [902081] [INFO] Worker exiting (pid: 902081)
[2024-03-08 21:15:12 +0000] [902082] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/DevOpsFlasked/main.py", line 3, in <module>
    app = create_app()
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/__init__.py", line 33, in create_app
    from .blog import blog
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 58
    return render_template('blogpost.html', post=post_deserialized, post_content_test=)
                                                                                      ^
SyntaxError: invalid syntax
[2024-03-08 21:15:12 +0000] [902082] [INFO] Worker exiting (pid: 902082)
[2024-03-08 21:15:14 +0000] [902083] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:15:14 +0000] [902083] [INFO] Listening at: unix:/run/gunicorn.sock (902083)
[2024-03-08 21:15:14 +0000] [902083] [INFO] Using worker: sync
[2024-03-08 21:15:14 +0000] [902086] [INFO] Booting worker with pid: 902086
[2024-03-08 21:15:14 +0000] [902087] [INFO] Booting worker with pid: 902087
[2024-03-08 21:15:14 +0000] [902088] [INFO] Booting worker with pid: 902088
[2024-03-08 21:15:28 +0000] [902083] [INFO] Handling signal: term
[2024-03-08 21:15:28 +0000] [902088] [INFO] Worker exiting (pid: 902088)
[2024-03-08 21:15:28 +0000] [902087] [INFO] Worker exiting (pid: 902087)
[2024-03-08 21:15:28 +0000] [902086] [INFO] Worker exiting (pid: 902086)
[2024-03-08 21:15:28 +0000] [902083] [WARNING] Worker with pid 902088 was terminated due to signal 15
[2024-03-08 21:15:29 +0000] [902083] [INFO] Shutting down: Master
[2024-03-08 21:15:30 +0000] [902123] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:15:30 +0000] [902123] [INFO] Listening at: unix:/run/gunicorn.sock (902123)
[2024-03-08 21:15:30 +0000] [902123] [INFO] Using worker: sync
[2024-03-08 21:15:30 +0000] [902126] [INFO] Booting worker with pid: 902126
[2024-03-08 21:15:30 +0000] [902127] [INFO] Booting worker with pid: 902127
[2024-03-08 21:15:30 +0000] [902128] [INFO] Booting worker with pid: 902128
[2024-03-08 21:21:18 +0000] [902123] [INFO] Handling signal: term
[2024-03-08 21:21:18 +0000] [902126] [INFO] Worker exiting (pid: 902126)
[2024-03-08 21:21:18 +0000] [902127] [INFO] Worker exiting (pid: 902127)
[2024-03-08 21:21:18 +0000] [902128] [INFO] Worker exiting (pid: 902128)
[2024-03-08 21:21:19 +0000] [902123] [WARNING] Worker with pid 902126 was terminated due to signal 15
[2024-03-08 21:21:19 +0000] [902123] [INFO] Shutting down: Master
[2024-03-08 21:21:20 +0000] [902356] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:21:20 +0000] [902356] [INFO] Listening at: unix:/run/gunicorn.sock (902356)
[2024-03-08 21:21:20 +0000] [902356] [INFO] Using worker: sync
[2024-03-08 21:21:20 +0000] [902359] [INFO] Booting worker with pid: 902359
[2024-03-08 21:21:20 +0000] [902360] [INFO] Booting worker with pid: 902360
[2024-03-08 21:21:20 +0000] [902361] [INFO] Booting worker with pid: 902361
[2024-03-08 21:22:13 +0000] [902356] [INFO] Handling signal: term
[2024-03-08 21:22:13 +0000] [902359] [INFO] Worker exiting (pid: 902359)
[2024-03-08 21:22:13 +0000] [902360] [INFO] Worker exiting (pid: 902360)
[2024-03-08 21:22:13 +0000] [902361] [INFO] Worker exiting (pid: 902361)
[2024-03-08 21:22:13 +0000] [902356] [WARNING] Worker with pid 902359 was terminated due to signal 15
[2024-03-08 21:22:14 +0000] [902356] [INFO] Shutting down: Master
[2024-03-08 21:22:17 +0000] [902460] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:22:17 +0000] [902460] [INFO] Listening at: unix:/run/gunicorn.sock (902460)
[2024-03-08 21:22:17 +0000] [902460] [INFO] Using worker: sync
[2024-03-08 21:22:17 +0000] [902463] [INFO] Booting worker with pid: 902463
[2024-03-08 21:22:17 +0000] [902464] [INFO] Booting worker with pid: 902464
[2024-03-08 21:22:17 +0000] [902465] [INFO] Booting worker with pid: 902465
[2024-03-08 21:25:19 +0000] [902460] [INFO] Handling signal: term
[2024-03-08 21:25:19 +0000] [902463] [INFO] Worker exiting (pid: 902463)
[2024-03-08 21:25:19 +0000] [902464] [INFO] Worker exiting (pid: 902464)
[2024-03-08 21:25:19 +0000] [902465] [INFO] Worker exiting (pid: 902465)
[2024-03-08 21:25:19 +0000] [902460] [WARNING] Worker with pid 902463 was terminated due to signal 15
[2024-03-08 21:25:19 +0000] [902460] [INFO] Shutting down: Master
[2024-03-08 21:25:22 +0000] [902678] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:25:22 +0000] [902678] [INFO] Listening at: unix:/run/gunicorn.sock (902678)
[2024-03-08 21:25:22 +0000] [902678] [INFO] Using worker: sync
[2024-03-08 21:25:22 +0000] [902681] [INFO] Booting worker with pid: 902681
[2024-03-08 21:25:22 +0000] [902682] [INFO] Booting worker with pid: 902682
[2024-03-08 21:25:22 +0000] [902683] [INFO] Booting worker with pid: 902683
[2024-03-08 21:29:14 +0000] [902678] [INFO] Handling signal: term
[2024-03-08 21:29:14 +0000] [902681] [INFO] Worker exiting (pid: 902681)
[2024-03-08 21:29:14 +0000] [902682] [INFO] Worker exiting (pid: 902682)
[2024-03-08 21:29:14 +0000] [902683] [INFO] Worker exiting (pid: 902683)
[2024-03-08 21:29:14 +0000] [902678] [WARNING] Worker with pid 902681 was terminated due to signal 15
[2024-03-08 21:29:14 +0000] [902678] [WARNING] Worker with pid 902682 was terminated due to signal 15
[2024-03-08 21:29:14 +0000] [902678] [INFO] Shutting down: Master
[2024-03-08 21:29:20 +0000] [902899] [INFO] Starting gunicorn 20.1.0
[2024-03-08 21:29:20 +0000] [902899] [INFO] Listening at: unix:/run/gunicorn.sock (902899)
[2024-03-08 21:29:20 +0000] [902899] [INFO] Using worker: sync
[2024-03-08 21:29:20 +0000] [902904] [INFO] Booting worker with pid: 902904
[2024-03-08 21:29:20 +0000] [902905] [INFO] Booting worker with pid: 902905
[2024-03-08 21:29:20 +0000] [902906] [INFO] Booting worker with pid: 902906
[2024-03-09 18:50:13 +0000] [902899] [INFO] Handling signal: term
[2024-03-09 18:50:13 +0000] [902904] [INFO] Worker exiting (pid: 902904)
[2024-03-09 18:50:13 +0000] [902905] [INFO] Worker exiting (pid: 902905)
[2024-03-09 18:50:13 +0000] [902906] [INFO] Worker exiting (pid: 902906)
[2024-03-09 18:50:13 +0000] [902899] [WARNING] Worker with pid 902904 was terminated due to signal 15
[2024-03-09 18:50:13 +0000] [902899] [WARNING] Worker with pid 902905 was terminated due to signal 15
[2024-03-09 18:50:13 +0000] [902899] [INFO] Shutting down: Master
[2024-03-09 18:50:19 +0000] [946324] [INFO] Starting gunicorn 20.1.0
[2024-03-09 18:50:19 +0000] [946324] [INFO] Listening at: unix:/run/gunicorn.sock (946324)
[2024-03-09 18:50:19 +0000] [946324] [INFO] Using worker: sync
[2024-03-09 18:50:19 +0000] [946329] [INFO] Booting worker with pid: 946329
[2024-03-09 18:50:19 +0000] [946330] [INFO] Booting worker with pid: 946330
[2024-03-09 18:50:19 +0000] [946331] [INFO] Booting worker with pid: 946331
[2024-03-16 19:57:23 +0000] [946324] [INFO] Handling signal: term
[2024-03-16 19:57:23 +0000] [946329] [INFO] Worker exiting (pid: 946329)
[2024-03-16 19:57:23 +0000] [946330] [INFO] Worker exiting (pid: 946330)
[2024-03-16 19:57:23 +0000] [946331] [INFO] Worker exiting (pid: 946331)
[2024-03-16 19:57:24 +0000] [946324] [INFO] Shutting down: Master
[2024-03-16 19:57:30 +0000] [1315075] [INFO] Starting gunicorn 20.1.0
[2024-03-16 19:57:30 +0000] [1315075] [INFO] Listening at: unix:/run/gunicorn.sock (1315075)
[2024-03-16 19:57:30 +0000] [1315075] [INFO] Using worker: sync
[2024-03-16 19:57:30 +0000] [1315080] [INFO] Booting worker with pid: 1315080
[2024-03-16 19:57:30 +0000] [1315081] [INFO] Booting worker with pid: 1315081
[2024-03-16 19:57:30 +0000] [1315082] [INFO] Booting worker with pid: 1315082
[2024-03-16 19:58:57 +0000] [1315075] [INFO] Handling signal: term
[2024-03-16 19:58:57 +0000] [1315080] [INFO] Worker exiting (pid: 1315080)
[2024-03-16 19:58:57 +0000] [1315081] [INFO] Worker exiting (pid: 1315081)
[2024-03-16 19:58:57 +0000] [1315082] [INFO] Worker exiting (pid: 1315082)
[2024-03-16 19:58:57 +0000] [1315075] [WARNING] Worker with pid 1315080 was terminated due to signal 15
[2024-03-16 19:58:58 +0000] [1315075] [INFO] Shutting down: Master
[2024-03-16 19:59:04 +0000] [1315310] [INFO] Starting gunicorn 20.1.0
[2024-03-16 19:59:04 +0000] [1315310] [INFO] Listening at: unix:/run/gunicorn.sock (1315310)
[2024-03-16 19:59:04 +0000] [1315310] [INFO] Using worker: sync
[2024-03-16 19:59:04 +0000] [1315315] [INFO] Booting worker with pid: 1315315
[2024-03-16 19:59:04 +0000] [1315316] [INFO] Booting worker with pid: 1315316
[2024-03-16 19:59:04 +0000] [1315317] [INFO] Booting worker with pid: 1315317
[2024-03-16 19:59:32 +0000] [1315310] [INFO] Handling signal: term
[2024-03-16 19:59:32 +0000] [1315315] [INFO] Worker exiting (pid: 1315315)
[2024-03-16 19:59:32 +0000] [1315316] [INFO] Worker exiting (pid: 1315316)
[2024-03-16 19:59:32 +0000] [1315317] [INFO] Worker exiting (pid: 1315317)
[2024-03-16 19:59:32 +0000] [1315310] [WARNING] Worker with pid 1315315 was terminated due to signal 15
[2024-03-16 19:59:33 +0000] [1315310] [INFO] Shutting down: Master
[2024-03-16 19:59:39 +0000] [1315411] [INFO] Starting gunicorn 20.1.0
[2024-03-16 19:59:39 +0000] [1315411] [INFO] Listening at: unix:/run/gunicorn.sock (1315411)
[2024-03-16 19:59:39 +0000] [1315411] [INFO] Using worker: sync
[2024-03-16 19:59:39 +0000] [1315416] [INFO] Booting worker with pid: 1315416
[2024-03-16 19:59:39 +0000] [1315417] [INFO] Booting worker with pid: 1315417
[2024-03-16 19:59:39 +0000] [1315418] [INFO] Booting worker with pid: 1315418
[2024-03-16 20:06:04 +0000] [1315411] [INFO] Handling signal: term
[2024-03-16 20:06:04 +0000] [1315416] [INFO] Worker exiting (pid: 1315416)
[2024-03-16 20:06:04 +0000] [1315417] [INFO] Worker exiting (pid: 1315417)
[2024-03-16 20:06:04 +0000] [1315418] [INFO] Worker exiting (pid: 1315418)
[2024-03-16 20:06:05 +0000] [1315411] [WARNING] Worker with pid 1315416 was terminated due to signal 15
[2024-03-16 20:06:05 +0000] [1315411] [INFO] Shutting down: Master
[2024-03-16 20:06:11 +0000] [1315803] [INFO] Starting gunicorn 20.1.0
[2024-03-16 20:06:11 +0000] [1315803] [INFO] Listening at: unix:/run/gunicorn.sock (1315803)
[2024-03-16 20:06:11 +0000] [1315803] [INFO] Using worker: sync
[2024-03-16 20:06:11 +0000] [1315808] [INFO] Booting worker with pid: 1315808
[2024-03-16 20:06:11 +0000] [1315809] [INFO] Booting worker with pid: 1315809
[2024-03-16 20:06:11 +0000] [1315810] [INFO] Booting worker with pid: 1315810
